version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: "your_secret"
      MONGO_URL: "mongodb://mongo:27017/talk-trove"
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
